# permissions for end users to edit ck8scontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ck8scontrolplane-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - ck8scontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - ck8scontrolplanes/status
  verbs:
  - get
