# permissions for end users to edit kthreescontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kthreescontrolplane-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kthreescontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kthreescontrolplanes/status
  verbs:
  - get
