version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/go-logr/logr
            - github.com/coredns/corefile-migration/migration
            - github.com/pkg/errors
            - k8s.io/api
            - k8s.io/apimachinery/pkg
            - k8s.io/apiserver
            - k8s.io/kubernetes
            - k8s.io/client-go
            - k8s.io/klog/v2
            - k8s.io/utils/ptr
            - github.com/onsi/ginkgo
            - github.com/onsi/gomega
            - sigs.k8s.io/yaml
            - sigs.k8s.io/controller-runtime
            - sigs.k8s.io/cluster-api
            - github.com/canonical/cluster-api-k8s
            - github.com/canonical/k8s-snap-api
            - github.com/google/uuid
            - github.com/pkg/errors
            - sigs.k8s.io/kind/pkg/errors
    godot:
      #   declarations - for top level declaration comments (default);
      #   toplevel     - for top level comments;
      #   all          - for all comments.
      scope: toplevel
      exclude:
        - ^ \+.*
        - ^ ANCHOR.*
    gomoddirectives:
      # List of allowed `replace` directives.
      # Default: []
      replace-allow-list:
        - sigs.k8s.io/cluster-api
    gosec:
      excludes:
        - G307 # Deferring unsafe method "Close" on type "\*os.File"
        - G108 # Profiling endpoint is automatically exposed on /debug/pprof
        - G115 # Integer overflow conversion int -> int32, Kubernetes replicas field is type int32
    importas:
      # Kubernetes
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
      # Do not allow unaliased imports of aliased packages.
      # Default: false
      no-unaliased: true
    nolintlint:
      # Enable to require nolint directives to mention the specific linter being suppressed.
      # Default: false
      require-specific: true
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: unused-parameter
          disabled: true
    tagliatelle:
      case:
        rules:
          # Any struct tag type can be used.
          # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`
          json: goCamel
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: test/e2e/*
        text: 'G106:'
      - linters:
          - revive
        path: .*test.*
        text: dot-imports
      - linters:
          - staticcheck
        path: .*test.*
        text: ST1001
    paths:
      - .*zz_generated.*\.go
      - contrib/.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/canonical/cluster-api-k8s)
    goimports:
      # put imports beginning with prefix after 3rd-party packages;
      # it's a comma-separated list of prefixes
      local-prefixes:
        - github.com/canonical/cluster-api-k8s
  exclusions:
    generated: lax
    paths:
      - .*zz_generated.*\.go
      - contrib/.*
      - third_party$
      - builtin$
      - examples$
