regions:
  - us-east-2

blocklist:
  - "999999999999" # A blocklist is required, but this is a placeholder

accounts:
  018302341396: {}

__global__:
  - property: tag
    type: glob
    value: "sigs.k8s.io/cluster-api-provider-aws/cluster/capick8s-*"

resource-types:
    includes:
      - EC2Instance
      - EC2SecurityGroup
      - EC2Volume
      - EC2InternetGateway
      - EC2InternetGatewayAttachment
      - EC2DHCPOption
      - EC2NetworkACL
      - EC2NATGateway
      - EC2RouteTable
      - EC2Subnet
      - EC2Volume
      - EC2VPC
      - EC2VPCEndpoint
      - EC2VPCEndpointServiceConfiguration
      - EC2Address
      - EC2NetworkInterface
      - EC2VPCEndpointConnection
      - EC2VPCPeeringConnection
      - EC2EgressOnlyInternetGateway
      - ELB
      - ELBv2
      - ELBv2TargetGroup
      - S3Bucket
      - AutoScalingGroup
      - AutoScalingLaunchConfiguration
