name: Security and quality nightly scan

on:
  # todo undo before merge
#  schedule:
#    - cron: '0 10 * * *'
  pull_request:

permissions:
  contents: read

jobs:
  TICS:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Save provider image
        run: |
          echo asf
